image: gitlab.nyrox.tech:5005/nyrox/shippy:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - shippy build --tag latest
    - shippy publish latest -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

