image: gitlab.nyrox.tech:5005/nyrox/longa:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - longa build --image $CI_COMMIT_REF_SLUG --tag latest
    - longa publish --image $CI_COMMIT_REF_SLUG --tag latest -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

