image: gitlab.nyrox.tech:5005/nyrox/longa:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - longa build --tag latest
    - longa publish latest -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

