image: gitlab.nyrox.tech:5005/nyrox/shippy:latest

build:
  stage: build
  script:
    - shippy build --tag latest

publish:
  stage: deploy
  script:
    - shippy publish latest -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD